# Generated by Django 5.0.4 on 2024-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
