# Generated by Django 5.0.4 on 2024-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_created_date_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order guide',
            field=models.IntegerField(default=0),
        ),
    ]
