# Generated by Django 5.0.4 on 2024-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_order_order_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order guide',
        ),
        migrations.AddField(
            model_name='order',
            name='guide',
            field=models.IntegerField(default=0, verbose_name='order guide'),
        ),
    ]
