# Generated by Django 5.0.4 on 2024-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_order_order_guide_order_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guide',
            field=models.IntegerField(default=10000000, verbose_name='order guide'),
        ),
    ]
