# Generated by Django 5.0.4 on 2024-04-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_platform',
            field=models.CharField(default='DROPI', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.deliverycompany'),
        ),
        migrations.CreateModel(
            name='Destributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.deliverycompany')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destributor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.destributor')),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.order')),
            ],
        ),
    ]
