# Generated by Django 5.0.4 on 2024-04-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_destributor_distributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
