# Generated by Django 5.0.4 on 2024-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='price',
            field=models.IntegerField(),
        ),
    ]
