# Generated by Django 5.0.4 on 2024-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_fee_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_2',
            new_name='customer_address_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='provider_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
