# Generated by Django 5.0.4 on 2024-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_address_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='date created'),
        ),
    ]
