# Generated by Django 5.0.4 on 2024-04-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='telepone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
