# Generated by Django 5.0.4 on 2024-04-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_distributor_telepone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='telepone',
            new_name='telephone',
        ),
    ]
